Repository gfx-rs/naga, pull requests merged in 2021-09, with the labels that each got.

#1321 hlsl: implement struct constructors
  src/back/hlsl/help.rs
  src/back/hlsl/mod.rs
  src/back/hlsl/writer.rs
  tests/in/operators.wgsl
  tests/out/glsl/operators.main.Compute.glsl
  tests/out/hlsl/interface.hlsl
  tests/out/hlsl/operators.hlsl
  tests/out/hlsl/quad-vert.hlsl
  tests/out/hlsl/quad.hlsl
  tests/out/hlsl/skybox.hlsl
  tests/out/msl/operators.msl
  tests/out/spv/operators.spvasm
  tests/out/wgsl/operators.wgsl
Labels: can backport

#1325 [glsl-out] Fix select order
  src/back/glsl/mod.rs
  tests/out/glsl/operators.main.Compute.glsl
Labels: can backport

#1326 [spv-in] Handle structs with no offset decorations
  src/front/glsl/offset.rs
  src/front/glsl/parser/declarations.rs
  src/front/mod.rs
  src/front/spv/mod.rs
Labels: can backport

#1333 Infer types of module-scope let declarations
  src/front/wgsl/mod.rs
  tests/in/operators.wgsl
Labels: can backport

#1334 spv-out: option to skip OpName for varyings
  src/back/spv/mod.rs
  src/back/spv/writer.rs
  tests/snapshots.rs
Labels: can backport

#1332 [wgsl-out] Correct production of `*` and `&` operators.
  src/back/wgsl/writer.rs
Labels: kind: bug, lang: WGSL, area: back-end

#1337 hlsl: avoid using texture keyword
  src/back/hlsl/help.rs
  tests/out/hlsl/image.hlsl
Labels: can backport

#1340 msl-out: fix as_type expressions
  src/back/msl/writer.rs
  tests/in/operators.wgsl
  tests/out/glsl/operators.main.Compute.glsl
  tests/out/hlsl/operators.hlsl
  tests/out/msl/access.msl
  tests/out/msl/image.msl
  tests/out/msl/operators.msl
  tests/out/spv/operators.spvasm
  tests/out/wgsl/operators.wgsl
Labels: can backport

#1360 [wgsl-in] Rework Load Rule handling and indirection.
  src/front/wgsl/mod.rs
  tests/out/glsl/access.foo.Vertex.glsl
  tests/out/glsl/boids.main.Compute.glsl
  tests/out/glsl/operators.main.Compute.glsl
  tests/out/glsl/shadow.fs_main.Fragment.glsl
  tests/out/hlsl/access.hlsl
  tests/out/hlsl/boids.hlsl
  tests/out/hlsl/operators.hlsl
  tests/out/hlsl/shadow.hlsl
  tests/out/msl/access.msl
  tests/out/msl/boids.msl
  tests/out/msl/operators.msl
  tests/out/msl/shadow.msl
  tests/out/spv/access.spvasm
  tests/out/spv/boids.spvasm
  tests/out/spv/bounds-check-zero.spvasm
  tests/out/spv/operators.spvasm
  tests/out/spv/shadow.spvasm
  tests/out/wgsl/access.wgsl
  tests/out/wgsl/boids.wgsl
  tests/out/wgsl/operators.wgsl
  tests/out/wgsl/shadow.wgsl
Labels: kind: bug, lang: WGSL, area: front-end

#1412 wgsl-out: update reserved words
  src/back/wgsl/keywords.rs
  tests/out/wgsl/931-constant-emitting-vert.wgsl
  tests/out/wgsl/constant-array-size-vert.wgsl
  tests/out/wgsl/prepostfix-frag.wgsl
Labels: can backport
