Repository gfx-rs/naga, pull requests merged in 2022-04, with the labels that each got.

#1812 Validate uniform address space layout constraints
  src/valid/type.rs
Labels: can backport

#1846 [hlsl-out] Emit `row_major` qualifier on matrix uniform globals.
  src/back/hlsl/writer.rs
  tests/out/hlsl/globals.hlsl
Labels: kind: bug, area: back-end, lang: HLSL

#1862 Clarify accepted types for `Expression::AccessIndex`
  src/lib.rs
Labels: area: doc

#1859 Document `TypeInner::BindingArray`.
  src/lib.rs
Labels: area: doc

#1872 Rename type flags to better align with the current WGSL spec.
  src/valid/interface.rs
  src/valid/type.rs
Labels: kind: refactor, area: middle

#1878 [glsl-in] Use `std::mem::take` as appropriate.
  src/front/glsl/mod.rs
Labels: kind: refactor, area: front-end, lang: GLSL

#1880 [glsl-in] Simplify control flow in search for `main`.
  src/front/glsl/parser.rs
Labels: kind: refactor, area: front-end, lang: GLSL
